name: Verify
on:
  schedule:
    - cron: "15 6 * * MON"
  pull_request: {}
  push: {}
jobs:
  tests:
    name: Run all Tests

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        browser: [firefox, chrome]
        include:
          - os: macos-latest
            browser: safari
          - os: windows-latest
            browser: MicrosoftEdge

    runs-on: ${{ matrix.os }}

    steps:
      - id: checkout
        name: Clone Git Repository
        uses: actions/checkout@v2
      - id: install
        name: Install Dependencies
        run: npm install
      - id: test
        name: Run Tests
        run: npm run test
        env:
          SELENIUM_BROWSER: ${{ matrix.browser }}
